config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, except: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :manager, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :contacts
  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def fullname
    first_name.capitalize + " " + last_name.capitalize + " | " + role
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:index, :show]
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action only: %i[index show create new]
  def index
    @contacts = Contact.all
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def new
    @contact = Contact.new
    @managers = User.all.where(manager: true)
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to contacts_path(@contacts)
    else
      render :new
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    redirect_to contacts_path(root_path)
  end

  private

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :address, :email, :manager_id, :department)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  def show
    authorize @user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to contacts_path
  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    if @user.update(update_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
  end

  private

  def user_params
    params.require(:user).permit(:manager, :admin)
  end

  def update_params
    params.require(:user).permit(:password)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/index.html.erb
<div class="container">
  <div class="contacts">
    <div class="contact-cards">
      <% @contacts.each do |contact| %>
      <div class="card">
        <%= link_to contact_path(contact), style: "width: 100%", class: "card-link" do %>
        <div class="contact-infos">
          <h2><%= contact.first_name.capitalize %></h2>
          <h2><%= contact.last_name.capitalize %></h2>
        </div>
          <p class="department">Department: <%= contact.department %></p>
        <% end  %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="container col-8">
  <h1 class="text-center my-3">Create a Contact</h1>

  <%= simple_form_for(@contact) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs" >
      <%= f.input :first_name %>
      <%= f.input :last_name %>
      <%= f.input :address %>
      <%= f.input :email %>
      <%= f.input :department %>
      <%= f.input :manager_id, collection: User.where(manager: true), label_method: :fullname %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, value: "Confirm & Submit", name: "submit", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/contacts/show.html.erb
<div class="container">
  <div class="contact">
    <div class="contact-card">
      <h2 class="card-title">Employee's Details:</h2>
      <h2 class="card-name"><%= @contact.first_name.capitalize %> <%= @contact.last_name.capitalize %></h2>
      <p class="infos_show">Email address: <%= @contact.email %></p>
      <p class="infos_show">Home address: <%= @contact.address %></p>
      <p class="infos_show">Department: <%= @contact.department %></p>
    </div>
    <div class="manager-card">
      <h2 class="card-title">Employee's Manager:</h2>
      <h2 class="card-name"><%= @contact.manager.first_name.capitalize %> <%= @contact.manager.last_name.capitalize %></h2>
      <p class="infos_show"><%= @contact.manager.role %></p>
      <hr>
      <p class="infos_show"><%= @contact.manager.email %></p>
    </div>
    <%= link_to "Back to Contacts", contacts_path, class: "btn btn-primary nav-link" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Contacts Manager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cdn.dribbble.com/users/79929/screenshots/2807602/sm-v4.3.png)">
      <div class="container" style="height: 100vh">
          <h1>Welcome to <strong>Your Contact Manager</strong> !</h1>
          <p>Create, Store & Contact</p>
          <%= link_to 'View Contacts', contacts_path, class: "btn btn-primary nav-link banner-btn" %>
         <!--     <a class="btn btn-flat" href="#">Apply now</a> -->
      </div>
    </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<script>
  const hideMessage = () => {
    const message = document.querySelector(".alert");
    message.style.display = "none";
  }
  setTimeout(function () {
    hideMessage();
  }, 5000);
</script>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-contact-manager">
  <%= link_to "My Contacts Manager", root_path, class: "btn btn-primary nav-link" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/Fred83200", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "New Contact", new_contact_path, class: "dropdown-item" %>
            <%= link_to "All Contacts", contacts_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "btn btn-primary nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>